language: csharp
solution: bill-payments-dotnet-sdk.sln

install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore bill-payments-dotnet-sdk.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  - if [[ $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_BRANCH = 'master' ]]; then openssl aes-256-cbc -K $encrypted_35f90653928635e2_key -iv $encrypted_35f90653928635e2_iv -in Qiwi.BillPayments.Tests/App.config.enc -out Qiwi.BillPayments.Tests/App.config -d; fi
script:
  - msbuild /p:Configuration=Release bill-payments-dotnet-sdk.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Qiwi.BillPayments.Tests/bin/Release/netcoreapp2.0/Qiwi.BillPayments.Tests.dll
