sudo: required
dist: trusty
language: csharp
solution: bill-payments-dotnet-sdk.sln
mono: 5.12.0
dotnet: 2.1.503
install:
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- if [[ $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_BRANCH = 'master' ]]; then openssl aes-256-cbc -K $encrypted_35f90653928635e2_key -iv $encrypted_35f90653928635e2_iv -in Qiwi.BillPayments.Tests/App.config.enc -out Qiwi.BillPayments.Tests/App.config -d; fi
script: dotnet test -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./**/*.nupkg -k $ApiKey -s https://api.nuget.org/v3/index.json -n true
  on:
    tags: true
    branches:
      only: master
